"""算法核心 —— 不依赖任何 UI 框架，可在子进程/工作线程中直接使用。"""

from .dsp import build_binary_mask, compute_column_field, hann_window, render_watermark
from .params import (
    DEFAULT_CUT_STRENGTH,
    DEFAULT_DRAW_STRENGTH,
    DEFAULT_FFT_SIZE,
    DRAW_LEVEL_MAX_DBFS,
    DRAW_LEVEL_MIN_DBFS,
    FFT_SIZE_CHOICES,
    MAX_DISPLAY_HZ,
    MAX_MASK_COLS,
    MIN_DISPLAY_HZ,
    MIN_MASK_COLS,
    DspSpec,
    EngraveMode,
    Interval,
    LoopSpec,
    PatternSource,
    PatternSpec,
    PlacementSpec,
    PositionMode,
    RenderJob,
    resolve_intervals,
)

__all__ = [
    "DspSpec",
    "EngraveMode",
    "Interval",
    "LoopSpec",
    "PatternSource",
    "PatternSpec",
    "PlacementSpec",
    "PositionMode",
    "RenderJob",
    "resolve_intervals",
    "build_binary_mask",
    "compute_column_field",
    "hann_window",
    "render_watermark",
    "DEFAULT_CUT_STRENGTH",
    "DEFAULT_DRAW_STRENGTH",
    "DEFAULT_FFT_SIZE",
    "DRAW_LEVEL_MIN_DBFS",
    "DRAW_LEVEL_MAX_DBFS",
    "FFT_SIZE_CHOICES",
    "MIN_MASK_COLS",
    "MAX_MASK_COLS",
    "MIN_DISPLAY_HZ",
    "MAX_DISPLAY_HZ",
]
